application: ebi-rideshare-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: main.app
builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

# builtins:
# - remote_api: on
# - datastore_admin: on

# handlers:
# - url: /static
#   static_dir: static

# - url: /.*
#   script: main.py

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
